USE [master]
GO
/****** Object:  Database [TodoListDB]    Script Date: 03/06/2025 08:41:42 ******/
ALTER DATABASE [TodoListDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoListDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TodoListDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TodoListDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TodoListDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TodoListDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TodoListDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TodoListDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TodoListDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TodoListDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TodoListDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TodoListDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TodoListDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TodoListDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TodoListDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TodoListDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TodoListDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TodoListDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TodoListDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TodoListDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TodoListDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TodoListDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TodoListDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TodoListDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TodoListDB] SET RECOVERY FULL 
GO
ALTER DATABASE [TodoListDB] SET  MULTI_USER 
GO
ALTER DATABASE [TodoListDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TodoListDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TodoListDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TodoListDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TodoListDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TodoListDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TodoListDB', N'ON'
GO
ALTER DATABASE [TodoListDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TodoListDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TodoListDB]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 03/06/2025 08:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Progression]    Script Date: 03/06/2025 08:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Progression](
	[Id] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Percent] [int] NOT NULL,
	[TodoItemId] [int] NOT NULL,
 CONSTRAINT [PK_Progression] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TodoItem]    Script Date: 03/06/2025 08:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TodoItem](
	[Id] [int] NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](100) NOT NULL,
	[Category] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_TodoItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Category] ON 

INSERT [dbo].[Category] ([Id], [Name]) VALUES (1, N'Sport')
INSERT [dbo].[Category] ([Id], [Name]) VALUES (2, N'Work')
SET IDENTITY_INSERT [dbo].[Category] OFF
GO
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (1, CAST(N'2025-03-20T00:00:00.000' AS DateTime), 20, 1)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (2, CAST(N'2025-03-18T00:00:00.000' AS DateTime), 30, 1)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (3, CAST(N'2025-03-19T00:00:00.000' AS DateTime), 50, 1)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (4, CAST(N'2025-05-27T00:00:00.000' AS DateTime), 10, 2)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (5, CAST(N'2025-05-29T00:00:00.000' AS DateTime), 10, 4)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (6, CAST(N'2025-05-27T00:00:00.000' AS DateTime), 30, 4)
INSERT [dbo].[Progression] ([Id], [Date], [Percent], [TodoItemId]) VALUES (7, CAST(N'2025-05-27T00:00:00.000' AS DateTime), 30, 3)
GO
INSERT [dbo].[TodoItem] ([Id], [Title], [Description], [Category]) VALUES (1, N'Complete Project Report', N'Finish the final report for the project', N'Work')
INSERT [dbo].[TodoItem] ([Id], [Title], [Description], [Category]) VALUES (2, N'Title2', N'Description2', N'Sport')
INSERT [dbo].[TodoItem] ([Id], [Title], [Description], [Category]) VALUES (3, N'Title3', N'Description Created from Postman 1', N'Sport')
INSERT [dbo].[TodoItem] ([Id], [Title], [Description], [Category]) VALUES (4, N'Test 4', N'Test 4444', N'Sport')
INSERT [dbo].[TodoItem] ([Id], [Title], [Description], [Category]) VALUES (5, N'Test 5', N'Test 66666666', N'Sport')
GO
USE [master]
GO
ALTER DATABASE [TodoListDB] SET  READ_WRITE 
GO
